add reset password function
bitfinexcom/bfx-facs-auth-google pull request #31
Opened 2024-01-04 12:26 UTC by jetmirsyla

2024-01-05 10:41 UTC, grantfayvor requested changes
some comments

2024-01-05 10:41 UTC, grantfayvor commented on index.js
> +        passwordResetToken TEXT,
add a migration for these fields in the migration file - https://github.com/bitfinexcom/bfx-facs-auth-google/blob/master/migrations.js

2024-01-05 10:41 UTC, grantfayvor commented on index.js
> +    let expiryDate = new Date(admin.passwordResetSentAt)
should be fine to use `const` here

```suggestion
    const expiryDate = new Date(admin.passwordResetSentAt)
```

2024-01-05 10:41 UTC, grantfayvor commented on index.js
> +      'analyticsPrivilege', 'manageAdminsPrivilege', 'readOnly', 'active', 'timestamp', 'passwordResetToken', 'passwordResetSentAt', FORMS_FIELD]
no reason to return these fields when fetching admins. they are only useful in the reset password process.

2024-01-08 09:36 UTC, grantfayvor approved these changes
lgtm!

2024-01-11 06:48 UTC, ezewer approved these changes
looks good to me!

2024-01-11 12:22 UTC, merged